# Generated by Django 3.1.3 on 2021-07-20 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='chats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, default='', max_length=3000000, null=True)),
                ('room', models.TextField(blank=True, default='', max_length=1024, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.TextField(blank=True, default='', max_length=3000000, null=True),
        ),
    ]
