# Generated by Django 3.1.3 on 2021-08-28 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20210720_2031'),
    ]

    operations = [
        migrations.CreateModel(
            name='chat_messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, default='', max_length=3000000, null=True)),
                ('room', models.TextField(blank=True, default='', max_length=3000000, null=True)),
                ('time', models.TimeField()),
                ('date', models.DateField()),
            ],
        ),
    ]
