# Generated by Django 3.1.3 on 2021-08-28 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chat_messages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat_messages',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chat_messages',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
